# Generated by Django 6.0.3 on 2026-03-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='component',
            name='updated_at',
        ),
    ]
