# Generated by Django 6.0.3 on 2026-03-17 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_component_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price_segment', models.CharField(choices=[('ECONOMY', 'Эконом'), ('STANDARD', 'Стандарт'), ('PREMIUM', 'Премиум')], max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_power', models.FloatField(default=0, verbose_name='Общее энергопотребление (Вт)')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('LIVING', 'Гостиная'), ('BEDROOM', 'Спальня'), ('KITCHEN', 'Кухня'), ('BATHROOM', 'Ванная'), ('CHILDREN', 'Детская'), ('OFFICE', 'Кабинет'), ('HALL', 'Прихожая'), ('OTHER', 'Другое')], max_length=50, verbose_name='Название')),
                ('area', models.FloatField(verbose_name='Площадь (м²)')),
            ],
        ),
        migrations.CreateModel(
            name='BuildComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.build')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.component')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.room')),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='components',
            field=models.ManyToManyField(through='catalog.BuildComponent', to='catalog.component'),
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_area', models.FloatField(verbose_name='Общая площадь')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rooms', models.ManyToManyField(to='catalog.room')),
            ],
        ),
    ]
