# Generated by Django 6.0.3 on 2026-03-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_build_room_buildcomponent_build_components_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Создана'), ('CONFIGURING', 'В настройке'), ('CHECKING', 'Проверяется'), ('NEEDS_FIX', 'Требует исправления'), ('VERIFIED', 'Проверена'), ('SAVED', 'Сохранена'), ('PENDING_MODERATION', 'На модерации'), ('PUBLISHED', 'Опубликована'), ('REJECTED', 'Отклонена'), ('ARCHIVED', 'Архивирована')], default='DRAFT', max_length=20, verbose_name='Статус сборки'),
        ),
    ]
