# Generated by Django 6.0.3 on 2026-03-18 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_build_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='Выбрана пользователем'),
        ),
        migrations.AddField(
            model_name='build',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='catalog.userproject', verbose_name='Проект'),
        ),
    ]
