# Generated by Django 6.0.3 on 2026-03-19 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_category_main_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_builds', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='build',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_builds', to=settings.AUTH_USER_MODEL, verbose_name='Сохранено пользователями'),
        ),
        migrations.AddField(
            model_name='build',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
