# Generated by Django 6.0.3 on 2026-03-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_build_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='description',
            field=models.TextField(blank=True, help_text='Расскажите о целях, особенностях и идее вашей сборки', verbose_name='Описание сборки'),
        ),
    ]
