# Generated by Django 6.0.3 on 2026-03-25 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('category', models.CharField(choices=[('BEGINNER', 'Для начинающих'), ('SETUP', 'Настройка'), ('SCENARIOS', 'Сценарии'), ('TROUBLESHOOTING', 'Решение проблем'), ('ADVANCED', 'Продвинутые советы')], default='BEGINNER', max_length=20, verbose_name='Категория')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('excerpt', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='guides/', verbose_name='Изображение')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guides', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Гайд',
                'verbose_name_plural': 'Гайды',
                'ordering': ['-created_at'],
            },
        ),
    ]
