# Generated by Django 6.0.3 on 2026-03-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='is_published',
        ),
        migrations.AddField(
            model_name='guide',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('PENDING', 'На модерации'), ('PUBLISHED', 'Опубликован'), ('REJECTED', 'Отклонён')], default='PENDING', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL'),
        ),
    ]
