# Generated by Django 6.0.3 on 2026-03-25 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_guide_is_published_guide_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='guides/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.guide')),
            ],
            options={
                'verbose_name': 'Изображение гайда',
                'verbose_name_plural': 'Изображения гайдов',
                'ordering': ['order'],
            },
        ),
    ]
